language: python
env:
    matrix:
        - BUILD="test"
        - BUILD="package"
install:
    - |
        if [[ $BUILD == 'test' ]]; \
        then \
        git clone https://github.com/Tsjerk/simopt.git && pip install ./simopt; \
        fi
    - |
        if [[ $BUILD == 'test' ]]; \
        then \
        pip install ./ ; \
        fi
    - |
        if [[ $BUILD == 'test' ]]; \
        then \
        pip install nose coverage; \
        fi
script:
    - |
        if [[ $BUILD == 'test' ]]; \
        then \
        cd tests && python run_tests.py -v --with-coverage --cover-package=insane; \
        fi
    - |
        if [[ $BUILD == 'package' ]]; \
        then \
        cd maintainers && ./zippackage.sh && ./insane -h; \
        fi
